title : Computational Dynamics
author: Angadh Nanjangud
logo: 'qe-logo-large.png'

# Short description about the book
description: >-
  An introduction to classical mechanics modeling and analysis with
  Python programming.

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
# repository:
#  url                         : https://github.com/executablebooks/quantecon-mini-example
#  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
